version: "3.4"

x-common-variables: &common-variables
  # MYSQL_USER: sampleuser
  # MYSQL_PASSWORD: samplepassword
  MYSQL_DATABASE: so6_sampledb
  DB_HOST: 127.0.0.1
  DB_NAME: so6-matrice
  MYSQL_USER: root
  MYSQL_PASSWORD: root
  DB_PORT: 5002
  SECRET: dmtqK?X$?F#9Xq3!

  # PORT: 5002
  REACT_APP_SERVER_PORT: 8000

services:
  mysql-db:
    image: mysql:5.7
    container_name: mysql_container_so6
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3002:3002
    restart: unless-stopped
    volumes:
      - ./db/sample/so6-db.sql:/docker-entrypoint-initdb.d/sample.sql
  phpmyadmin:
    depends_on:
      - mysql-db
    image: phpmyadmin/phpmyadmin
    container_name: phpadmin_container_so6
    environment:
      PMA_HOST: mysql-db
    links:
      - mysql-db:mysql-db
    ports:
      - 8080:80
    restart: always
  server:
    build: ./backend
    container_name: node_server_container
    depends_on:
      - mysql-db
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql-db
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app/src
    links:
      - mysql-db
    command: npm start
  client:
    build: ./frontend
    container_name: client_container
    environment:
      <<: *common-variables
      NODE_PATH: src
    ports:
      - 3000:3000
    volumes: 
      - ./frontend:/app/src
      # - ./my_image
      # - ./frontend/src:/app/src
      
    links:
      # - ./server
      - mysql-db:mysql-db
    command: npm run dev