version: "3.7"

x-common-variables: &common-variables
  MYSQL_USER: localhost
  MYSQL_ALLOW_EMPTY_PASSWORD: 1
  MYSQL_DATABASE: so6
  REACT_APP_SERVER_PORT: 5000

  DB_HOST: "localhost"
  DB_NAME: "so6"
  DB_USER: "root"
  DB_PW: ""
  DB_PORT: 3306

  PORT: 5000
  PORT_TEST: 5001

services:
  mysql-db:
    image: mysql:5.7
    container_name: mysql_so6
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
    - ./db/sample.sql:/docker-entrypoint-initdb.d/sample.sql
  phpmyadmin:
    depends_on:
      - mysql-db
    image: phpmyadmin/phpmyadmin
    container_name: phpadmin_so6
    environment:
      PMA_HOST: mysql-db
    links:
      - mysql-db:mysql-db
    ports:
      - 8080:80
    restart: always
  backend:
    build: ./backend
    container_name: node_backend_so6
    depends_on:
      - mysql-db
    environment:
      <<: *common-variables
      # MYSQL_HOST_IP: mysql-db
      DB_HOST: mysql-db
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
    links:
      - mysql-db
  frontend:
    build: ./frontend
    container_name: frontend_so6
    environment:
      <<: *common-variables
      NODE_PATH: src
    ports:
      - 5173:5173
    volumes:
      - ./frontend/src:/app/src
    links:
      - backend